name: Build GhostTeleKill NDK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: |
          yes | sdkmanager --licenses
          yes | sdkmanager "ndk;26.3.11579264"
          echo "NDK=$ANDROID_SDK_ROOT/ndk/26.3.11579264" >> $GITHUB_ENV

      - name: Prepare folders
        run: |
          mkdir -p app/src/main/jni
          mkdir -p app/src/main/libs

      - name: Create Android.mk
        run: |
          echo 'LOCAL_PATH := $(call my-dir)' > app/src/main/jni/Android.mk
          echo 'include $(CLEAR_VARS)' >> app/src/main/jni/Android.mk
          echo 'LOCAL_MODULE := ghost_telekill' >> app/src/main/jni/Android.mk
          echo 'LOCAL_SRC_FILES := ghost_telekill.c' >> app/src/main/jni/Android.mk
          echo 'LOCAL_LDLIBS := -llog -lm' >> app/src/main/jni/Android.mk
          echo 'include $(BUILD_SHARED_LIBRARY)' >> app/src/main/jni/Android.mk

      - name: Create Application.mk
        run: |
          echo 'APP_ABI := armeabi-v7a arm64-v8a x86 x86_64' > app/src/main/jni/Application.mk
          echo 'APP_PLATFORM := android-21' >> app/src/main/jni/Application.mk
          echo 'APP_STL := c++_static' >> app/src/main/jni/Application.mk

      - name: Create source
        run: |
          echo '#include <jni.h>' > app/src/main/jni/ghost_telekill.c
          echo '#include <android/log.h>' >> app/src/main/jni/ghost_telekill.c
          echo '#define LOG_TAG "GhostTeleKill"' >> app/src/main/jni/ghost_telekill.c
          echo '#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)' >> app/src/main/jni/ghost_telekill.c
          echo 'JNIEXPORT void JNICALL Java_test(JNIEnv* env, jobject obj){ LOGI("GhostTeleKill Loaded"); }' >> app/src/main/jni/ghost_telekill.c

      - name: Build
        run: |
          $NDK/ndk-build \
          NDK_PROJECT_PATH=. \
          APP_BUILD_SCRIPT=app/src/main/jni/Android.mk \
          NDK_APPLICATION_MK=app/src/main/jni/Application.mk \
          NDK_LIBS_OUT=app/src/main/libs \
          APP_ABI=${{ matrix.abi }}

      - name: Upload .so
        uses: actions/upload-artifact@v4
        with:
          name: ghost-${{ matrix.abi }}
          path: app/src/main/libs/${{ matrix.abi }}/libghost_telekill.so
